name: Submit Dependency Graph

on:
  push:
    # Trigger on push to the main branch to keep the graph updated
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  dependency_submission:
    runs-on: ubuntu-latest

    # Grant permission to the GITHUB_TOKEN to write security events
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        # Use the Java version required by your project (e.g., '17')
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Submit Gradle Dependency Snapshot
        # This action executes Gradle dependency resolution and submits the result
        uses: mikepenz/gradle-dependency-submission@v1
        with:
          gradle-build-module: |-
            :
